### ISSUE TITLE
invalid timezones

### ISSUE THREAD

**Issue by fdncred** [qtfkwk/dtg#3]
I'm facing this issue in another project and wondering if you can help. First, very nice job on dtg. I really like it. Not that much code and easy to understand.

My question revolves around specifying timezones. If I run your code with `cargo r -- -z CDT` it comes back and says that "ERROR: Invalid timezone: `CDT`!" but if I do this `cargo r -- -z US/Central` it reports the time properly but the timezone is `CDT`, like `Sun 21 May 2023 08:53:37 CDT`.

What I'm wondering is if there's a way to have CDT (and others like it) recognized as a timezone instead of saying it's invalid. Any ideas?

**Comment by qtfkwk** [comment]
dtg's time zone names come from [`chrono_tz::TZ_VARIANTS`](https://docs.rs/chrono-tz/latest/chrono_tz/static.TZ_VARIANTS.html)... and `CDT` is not a valid time zone.

dtg provides the `-Z` option to discover valid time zone names which takes an argument to search case insensitively:

```text
$ cargo r -- -Z cdt
CST5CDT
```

So instead of `CDT`, you want `CST5CDT`, or you can also use `US/Central`.

Hopefully this helps!

**Comment by fdncred** [comment]
Right, I understand what you're saying and how "valid" means according to TZ_VARIANTS, but if it wasn't a valid timezone, why does it report the timezone like ```
Sun 21 May 2023 08:53:37 CDT
```
It seems that if it were "invalid" it wouldn't report "invalid" timezones when it's printing out this information. That's where the confusion lies.

I also noticed that it was in https://github.com/terhechte/timezone-abbreviations.

I know you're not the keeper of all timezone information, I just thought you would have some other wisdom to share. Thanks again.
